# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "kites", :force => true do |t|
    t.column "name",            :string
    t.column "namespace",       :string
    t.column "script",          :text
    t.column "default_task_id", :integer
    t.column "description",     :text
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "tasks", :force => true do |t|
    t.column "name",        :string
    t.column "kite_id",     :integer
    t.column "description", :text
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

end
